# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(default=2016, max_length=255, unique=True),
        ),
    ]
