# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0003_auto_20161103_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('companies', models.ManyToManyField(to='congress.Company')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.Edition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.ActivityFormat'),
        ),
        migrations.AddField(
            model_name='activity',
            name='speakers',
            field=models.ManyToManyField(to='congress.Speaker'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(to='congress.Tag'),
        ),
        migrations.AddField(
            model_name='activity',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congress.Track'),
        ),
    ]
