# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0004_auto_20161103_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
