# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:02
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0005_auto_20161103_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
