# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0006_edition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congress.Company'),
        ),
    ]
