# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0007_auto_20161103_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='linked_in_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
